version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/plugins/dsc/shared"
    target-branch: "source"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "06:00"
      timezone: "America/Chicago"
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"
